# chain sdk
ChainClient:
  ChainId: "lcago"
  SdkConfigPath: "./conf/lcago_sdk.yml"
  DefaultHeight: 60000
  ContractName: "cc4"
# mysql 数据库
MySQL:
  Host: 192.168.0.91
  Port: 33060
  User: "root"
  Password: "lcago@bc"
  DBName: "chain_proxy"
  Parameters: "charset=utf8mb4&parseTime=True&loc=Local"
# gorm相关设置
Gorm:
  Debug: true
  DBType: "mysql"
  MaxOpenConns: 100
  MaxLifetime: 10
  MaxIdleConns: 100
  EnableAutoMigrate: true